export interface Technique {
  id: string;
  name: string;
  category: 'recon' | 'mitigation' | 'technique' | 'leaf';
  stack: string[];
  format: string[];
  heap: string[];
  sandbox: string[];
  description: string;
  prerequisites: string[];
  constraints: string[];
  blueprint: string;
  children?: string[];
}

export const PWN_TECHNIQUES: Record<string, Technique> = {
  root: {
    id: 'root',
    name: 'PWN Exploitation Tree',
    category: 'root',
    stack: [],
    format: [],
    heap: [],
    sandbox: [],
    description: 'Interactive decision tree for exploitation techniques across different vulnerability types',
    prerequisites: [],
    constraints: [],
    blueprint: 'framework.init() {\n  analyze_target();\n  identify_vulns();\n  develop_exploit();\n}',
    children: ['buffer_overflow', 'format_string', 'heap_exploit', 'sandbox_escape', 'fsop_exploit', 'integer_exploits', 'mitigations_root', 'recon_tools_root'],
  },

  // MITIGATIONS BRANCH
  mitigations_root: {
    id: 'mitigations_root',
    name: 'Binary Protections',
    category: 'root',
    stack: [],
    format: [],
    heap: [],
    sandbox: [],
    description: 'Security features designed to prevent or mitigate exploitation of vulnerabilities',
    prerequisites: [],
    constraints: [],
    blueprint: 'analyze_mitigations() {\n  run("checksec --file=./binary");\n  identify_enabled_protections();\n  plan_bypasses();\n}',
    children: ['aslr_prot', 'nx_prot', 'canary_prot', 'relro_prot'],
  },

  aslr_prot: {
    id: 'aslr_prot',
    name: 'ASLR / PIE',
    category: 'mitigation',
    stack: [],
    format: [],
    heap: [],
    sandbox: [],
    description: 'Address Space Layout Randomization & Position Independent Executable randomizes memory segments',
    prerequisites: ['Kernel support', 'Compiler flags'],
    constraints: ['Must leak an address to bypass'],
    blueprint: 'aslr_defense() {\n  echo 2 > /proc/sys/kernel/randomize_va_space;\n  // gcc -pie -fPIE\n}',
    children: ['info_leak_bypass', 'partial_overwrite'],
  },

  info_leak_bypass: {
    id: 'info_leak_bypass',
    name: 'Information Leak',
    category: 'technique',
    stack: [],
    format: [],
    heap: [],
    sandbox: [],
    description: 'Leaking a pointer to calculate the base address of a randomized region',
    prerequisites: ['Out-of-bounds read or format string'],
    constraints: [],
    blueprint: 'bypass_aslr_leak() {\n  const leak = trigger_oob_read();\n  const libc_base = leak - offset_in_libc;\n  const system_addr = libc_base + system_offset;\n}',
    children: [],
  },

  partial_overwrite: {
    id: 'partial_overwrite',
    name: 'Partial Overwrite',
    category: 'technique',
    stack: [],
    format: [],
    heap: [],
    sandbox: [],
    description: 'Overwriting only the least significant bytes of a pointer to bypass ASLR without a leak',
    prerequisites: ['Little-endian architecture', 'Target on same page'],
    constraints: ['May require brute-forcing nibbles'],
    blueprint: 'partial_overwrite() {\n  // Overwrite the last 2 bytes of a pointer\n  // Need 1/16 luck if ASLR nibble is randomized\n  payload = p16(0x1234);\n  write_memory(target, payload);\n}',
    children: [],
  },

  nx_prot: {
    id: 'nx_prot',
    name: 'NX (No-Execute)',
    category: 'mitigation',
    stack: [],
    format: [],
    heap: [],
    sandbox: [],
    description: 'Marks memory regions (like the stack and heap) as non-executable to prevent shellcode execution',
    prerequisites: ['Hardware NX bit support'],
    constraints: ['Forces attacker to use code-reuse attacks'],
    blueprint: 'nx_defense() {\n  // Page tables mark stack/heap segments\n  // without the executable permission bit\n  // gcc -Wl,-z,noexecstack\n}',
    children: ['rop_bypass'],
  },

  rop_bypass: {
    id: 'rop_bypass',
    name: 'Code Reuse (ROP)',
    category: 'leaf',
    stack: [],
    format: [],
    heap: [],
    sandbox: [],
    description: 'Chaining existing executable code snippets to bypass NX',
    prerequisites: ['Known executable memory addresses'],
    constraints: [],
    blueprint: 'bypass_nx_rop() {\n  // Use tools like ROPgadget or ropper\n  chain = p64(pop_rdi) + p64(bin_sh) + p64(system);\n  send_payload(padding + chain);\n}',
    children: [],
  },

  canary_prot: {
    id: 'canary_prot',
    name: 'Stack Canaries',
    category: 'mitigation',
    stack: [],
    format: [],
    heap: [],
    sandbox: [],
    description: 'A random value placed before the saved return pointer to detect stack buffer overflows',
    prerequisites: ['Compiler flag (-fstack-protector)'],
    constraints: ['Must be leaked or bypassed to overwrite RIP'],
    blueprint: 'canary_defense() {\n  // gcc -fstack-protector-all\n  setup_canary() {\n    rax = fs:0x28;\n    [rbp-0x8] = rax;\n  }\n}',
    children: ['canary_leak', 'canary_bruteforce'],
  },

  canary_leak: {
    id: 'canary_leak',
    name: 'Canary Leak',
    category: 'leaf',
    stack: [],
    format: [],
    heap: [],
    sandbox: [],
    description: 'Reading the canary value using a format string or OOB read before returning',
    prerequisites: ['Read primitive'],
    constraints: [],
    blueprint: 'leak_canary() {\n  // %N$p where N is canary offset\n  canary = parse_hex(send_fmt_string("%15$p"));\n  payload = pad + p64(canary) + p64(0) + p64(rip);\n}',
    children: [],
  },

  canary_bruteforce: {
    id: 'canary_bruteforce',
    name: 'Canary Bruteforce',
    category: 'leaf',
    stack: [],
    format: [],
    heap: [],
    sandbox: [],
    description: 'Bruteforcing the canary byte-by-byte in forking servers',
    prerequisites: ['Forking network server'],
    constraints: ['Server must not crash the main process on bad canary'],
    blueprint: 'brute_canary() {\n  canary = "\\x00";\n  for (let i = 1; i < 8; i++) {\n    for (let b = 0; b < 256; b++) {\n      if (test_byte(canary + chr(b))) canary += chr(b);\n    }\n  }\n}',
    children: [],
  },

  relro_prot: {
    id: 'relro_prot',
    name: 'RELRO',
    category: 'mitigation',
    stack: [],
    format: [],
    heap: [],
    sandbox: [],
    description: 'Relocation Read-Only hardens ELF programs against GOT overwrites',
    prerequisites: ['Compiler flags (-z relro, -z now)'],
    constraints: ['Full RELRO makes GOT read-only'],
    blueprint: 'relro_defense() {\n  // Full RELRO: gcc -Wl,-z,relro,-z,now\n  // Partial RELRO: gcc -Wl,-z,relro,-z,lazy\n}',
    children: ['relro_bypass'],
  },

  relro_bypass: {
    id: 'relro_bypass',
    name: 'Hook Overwrite / FSOP',
    category: 'leaf',
    stack: [],
    format: [],
    heap: [],
    sandbox: [],
    description: 'Bypassing Full RELRO by targeting writable function pointers elsewhere (e.g. __free_hook, _IO_FILE vtables)',
    prerequisites: ['Arbitrary write primitive'],
    constraints: [],
    blueprint: 'bypass_relro() {\n  // Target __free_hook instead of GOT\n  free_hook_addr = libc_base + free_hook_offset;\n  arbitrary_write(free_hook_addr, system_addr);\n  free(ptr_to_bin_sh);\n}',
    children: [],
  },

  // RECONNAISSANCE BRANCH
  recon_tools_root: {
    id: 'recon_tools_root',
    name: 'Reconnaissance Methodology',
    category: 'root',
    stack: [],
    format: [],
    heap: [],
    sandbox: [],
    description: 'Systematic approaches to gathering information about a target binary',
    prerequisites: [],
    constraints: [],
    blueprint: 'recon_methodology() {\n  run("file ./binary");\n  run("checksec ./binary");\n  open_in_ghidra_or_ida();\n  attach_pwndbg();\n}',
    children: ['static_analysis', 'dynamic_analysis'],
  },

  static_analysis: {
    id: 'static_analysis',
    name: 'Static Analysis',
    category: 'recon',
    stack: [],
    format: [],
    heap: [],
    sandbox: [],
    description: 'Analyzing the binary without executing it (disassembly, decompilation, structure analysis)',
    prerequisites: ['Binary file access'],
    constraints: ['Obfuscation/packing can hinder analysis'],
    blueprint: '1. checksec\n2. strings / rabin2\n3. IDA Pro / Ghidra',
    children: [],
  },

  dynamic_analysis: {
    id: 'dynamic_analysis',
    name: 'Dynamic Analysis',
    category: 'recon',
    stack: [],
    format: [],
    heap: [],
    sandbox: [],
    description: 'Observing the binary\'s behavior during execution (debugging, tracing)',
    prerequisites: ['Execution environment', 'Debugger'],
    constraints: ['Anti-debugging techniques'],
    blueprint: '1. ltrace / strace\n2. GDB + pwndbg\n3. Fuzzing',
    children: [],
  },

  // BUFFER OVERFLOW BRANCH
  buffer_overflow: {
    id: 'buffer_overflow',
    name: 'Buffer Overflow',
    category: 'recon',
    stack: ['stack-based'],
    format: [],
    heap: [],
    sandbox: [],
    description: 'Exploits by overwriting stack buffers to redirect execution flow',
    prerequisites: ['No ASLR', 'No Stack Canaries', 'Vulnerable input handling'],
    constraints: ['Requires buffer size knowledge', 'Address space must be predictable'],
    blueprint: 'buffer_overflow_exploit() {\n  const payload = craft_rop_chain();\n  trigger_vulnerable_function(payload);\n  hijack_execution_flow();\n}',
    children: ['stack_pivot', 'rop_chain', 'ret2csu', 'ret2dlresolve', 'srop', 'stack_clash', 'brop', 'jop', 'ret2vdso'],
  },

  brop: {
    id: 'brop',
    name: 'Blind ROP (BROP)',
    category: 'technique',
    stack: ['stack-based'],
    format: [],
    heap: [],
    sandbox: [],
    description: 'Bypassing ASLR/NX remotely without having the binary by byte-by-byte brute-forcing gadgets and the PLT.',
    prerequisites: ['Server that restarts on crash', 'No PIE (or bruteforceable PIE)'],
    constraints: ['Requires thousands of requests'],
    blueprint: 'brop() {\n  find_stop_gadget();\n  find_brop_gadget();\n  find_puts_plt();\n  dump_binary();\n}',
    children: ['rop_exec'],
  },

  jop: {
    id: 'jop',
    name: 'Jump Oriented Programming (JOP)',
    category: 'technique',
    stack: ['stack-based'],
    format: [],
    heap: [],
    sandbox: [],
    description: 'Code reuse attack that relies on indirect jumps/calls instead of returns to bypass protections like Shadow Stacks (CET).',
    prerequisites: ['Dispatcher gadget', 'Predictable jump tables'],
    constraints: ['Finding a suitable dispatcher loop is difficult'],
    blueprint: 'jop() {\n  setup_dispatcher();\n  chain_jmp_rax_gadgets();\n}',
    children: ['rop_exec'],
  },

  ret2vdso: {
    id: 'ret2vdso',
    name: 'ret2vdso',
    category: 'technique',
    stack: ['stack-based'],
    format: [],
    heap: [],
    sandbox: [],
    description: 'Exploiting the kernel-provided vDSO (virtual dynamic shared object) mapped in user-space to execute syscalls like gettimeofday/rt_sigreturn.',
    prerequisites: ['vDSO mapped', 'ASLR bypass for vDSO'],
    constraints: ['vDSO randomization'],
    blueprint: 'ret2vdso() {\n  leak_vdso();\n  call_sigreturn_vdso();\n}',
    children: ['srop'],
  },

  stack_pivot: {
    id: 'stack_pivot',
    name: 'Stack Pivot',
    category: 'technique',
    stack: ['stack-based'],
    format: [],
    heap: [],
    sandbox: [],
    description: 'Manipulates ESP/RSP to control stack layout and gadget execution',
    prerequisites: ['ROP gadgets available', 'Writable memory regions'],
    constraints: ['Address layout predictability required'],
    blueprint: 'pivot_stack() {\n  const new_stack = find_writable_region();\n  set_rsp(new_stack);\n  execute_gadget_chain();\n}',
    children: ['rop_exec', 'heap_spray'],
  },

  rop_chain: {
    id: 'rop_chain',
    name: 'ROP Chain',
    category: 'technique',
    stack: ['stack-based'],
    format: [],
    heap: [],
    sandbox: [],
    description: 'Links return-oriented programming gadgets to execute arbitrary code',
    prerequisites: ['Gadget finder output', 'Binary analysis'],
    constraints: ['Gadget availability', 'Instruction alignment'],
    blueprint: 'rop_exploit() {\n  const gadgets = find_gadgets(binary);\n  const chain = build_chain(gadgets, payload);\n  execute_chain(chain);\n}',
    children: ['rop_exec'],
  },

  rop_exec: {
    id: 'rop_exec',
    name: 'ROP Execution',
    category: 'leaf',
    stack: ['stack-based'],
    format: [],
    heap: [],
    sandbox: [],
    description: 'Final execution stage using ROP gadgets to call system functions',
    prerequisites: ['Complete ROP chain', 'Target function addressable'],
    constraints: ['Call convention compliance', 'Register state'],
    blueprint: 'exec_rop() {\n  // Load system() address\n  mov rdi, "/bin/sh";\n  call system_addr;\n  // Execute shell\n}',
    children: [],
  },

  ret2csu: {
    id: 'ret2csu',
    name: 'Ret2csu',
    category: 'technique',
    stack: ['stack-based'],
    format: [],
    heap: [],
    sandbox: [],
    description: 'Uses gadgets from __libc_csu_init to populate rdx, rsi, rdi and call functions',
    prerequisites: ['x64 dynamically linked binary', '__libc_csu_init present'],
    constraints: ['Needs specific gadget layout from glibc'],
    blueprint: 'ret2csu() {\n  call csu_gadget_1;\n  call csu_gadget_2;\n}',
    children: ['rop_exec'],
  },

  ret2dlresolve: {
    id: 'ret2dlresolve',
    name: 'Ret2dl-resolve',
    category: 'technique',
    stack: ['stack-based'],
    format: [],
    heap: [],
    sandbox: [],
    description: 'Forces the dynamic linker to resolve an arbitrary function (like system) instead of a legit one',
    prerequisites: ['No RELRO or Partial RELRO', 'No PIE (typically)', 'Large buffer space'],
    constraints: ['Complex payload setup'],
    blueprint: 'ret2dl() {\n  fake_reloc();\n  fake_symtab();\n  call_dl_resolve();\n}',
    children: ['rop_exec'],
  },

  srop: {
    id: 'srop',
    name: 'SROP',
    category: 'technique',
    stack: ['stack-based'],
    format: [],
    heap: [],
    sandbox: [],
    description: 'Sigreturn Oriented Programming - fakes a signal frame on the stack to set all registers at once',
    prerequisites: ['Control over RAX', 'sigreturn syscall gadget', 'Large stack buffer'],
    constraints: ['Requires ~300 bytes of overflow space'],
    blueprint: 'srop() {\n  set_rax_15();\n  syscall(); // sigreturn with fake frame\n}',
    children: ['rop_exec'],
  },

  stack_clash: {
    id: 'stack_clash',
    name: 'Stack Clash',
    category: 'technique',
    stack: ['stack-based'],
    format: [],
    heap: [],
    sandbox: [],
    description: 'Jumps the stack guard page to clash with the heap or other memory regions',
    prerequisites: ['Large stack allocation', 'VLA or alloca() usage'],
    constraints: ['OS/Kernel patch dependent'],
    blueprint: 'clash() {\n  alloc_huge_stack();\n  touch_pages();\n  overwrite_target();\n}',
    children: [],
  },

  heap_spray: {
    id: 'heap_spray',
    name: 'Heap Spray',
    category: 'leaf',
    stack: [],
    format: [],
    heap: ['heap-based'],
    sandbox: [],
    description: 'Allocates massive heap objects to occupy predictable memory addresses',
    prerequisites: ['Heap allocator control', 'Large memory available'],
    constraints: ['Memory pressure limits', 'Allocator implementation knowledge'],
    blueprint: 'spray_heap() {\n  for (let i = 0; i < 0x10000; i++) {\n    allocate(SPRAY_SIZE);\n  }\n}',
    children: [],
  },

  // FORMAT STRING BRANCH
  format_string: {
    id: 'format_string',
    name: 'Format String',
    category: 'recon',
    stack: [],
    format: ['format-string'],
    heap: [],
    sandbox: [],
    description: 'Exploits unvalidated printf-style format strings to leak/write memory',
    prerequisites: ['Unvalidated user input', 'Format function usage'],
    constraints: ['Format string position discovery', 'Address alignment'],
    blueprint: 'format_string_exploit() {\n  const offset = discover_offset();\n  const payload = "%x".repeat(offset) + "%n";\n  leak_memory(payload);\n}',
    children: ['format_leak', 'format_write', 'blind_format', 'stack_chk_fail_hijack'],
  },

  format_leak: {
    id: 'format_leak',
    name: 'Memory Leak via %x',
    category: 'technique',
    stack: [],
    format: ['format-string'],
    heap: [],
    sandbox: [],
    description: 'Reads stack/memory values using format string read specifiers',
    prerequisites: ['Format string position known'],
    constraints: ['Offset precision required'],
    blueprint: 'leak_via_format() {\n  const payload = "%p %p %p %p";\n  return format_function(payload);\n}',
    children: ['leak_libc', 'leak_stack'],
  },

  format_write: {
    id: 'format_write',
    name: 'Memory Write via %n',
    category: 'technique',
    stack: [],
    format: ['format-string'],
    heap: [],
    sandbox: [],
    description: 'Writes arbitrary values to memory using %n specifier',
    prerequisites: ['Target address known', 'Format position known'],
    constraints: ['Alignment requirements', 'Byte-by-byte writing needed'],
    blueprint: 'write_via_format() {\n  const target = get_got_entry();\n  const payload = build_format_write(target, value);\n  format_function(payload);\n}',
    children: ['got_overwrite'],
  },

  leak_libc: {
    id: 'leak_libc',
    name: 'Leak libc Address',
    category: 'leaf',
    stack: [],
    format: ['format-string'],
    heap: [],
    sandbox: [],
    description: 'Extracts libc base address for ASLR bypass',
    prerequisites: ['libc symbol addressable', 'Format position discovered'],
    constraints: ['Predictable libc offset', 'Symbol must be on stack'],
    blueprint: 'leak_libc_addr() {\n  const payload = craft_leak_payload();\n  const leaked = format_function(payload);\n  return subtract_offset(leaked, LIBC_OFFSET);\n}',
    children: [],
  },

  leak_stack: {
    id: 'leak_stack',
    name: 'Leak Stack Values',
    category: 'leaf',
    stack: [],
    format: ['format-string'],
    heap: [],
    sandbox: [],
    description: 'Reads values directly from the stack for information disclosure',
    prerequisites: ['Stack layout known'],
    constraints: ['Address range limitations'],
    blueprint: 'leak_stack() {\n  const payload = "%x ".repeat(20);\n  return format_function(payload);\n}',
    children: [],
  },

  got_overwrite: {
    id: 'got_overwrite',
    name: 'GOT Overwrite',
    category: 'leaf',
    stack: [],
    format: ['format-string'],
    heap: [],
    sandbox: [],
    description: 'Overwrites Global Offset Table entries to hijack function calls',
    prerequisites: ['Target GOT address known', '%n capability'],
    constraints: ['Got entry must be writable'],
    blueprint: 'overwrite_got() {\n  const got_addr = find_got_entry(target_func);\n  const payload = write_payload(got_addr, shell_addr);\n  format_function(payload);\n}',
    children: [],
  },

  stack_chk_fail_hijack: {
    id: 'stack_chk_fail_hijack',
    name: '__stack_chk_fail Hijack',
    category: 'leaf',
    stack: [],
    format: ['format-string'],
    heap: [],
    sandbox: [],
    description: 'Overwriting the GOT entry of __stack_chk_fail so that triggering a stack smash executes arbitrary code instead of aborting.',
    prerequisites: ['Format string write primitive', 'Stack canary enabled'],
    constraints: ['Partial RELRO only'],
    blueprint: 'hijack_chk_fail() {\n  fmt_overwrite(got_stack_chk_fail, system);\n  trigger_stack_smash();\n}',
    children: [],
  },

  blind_format: {
    id: 'blind_format',
    name: 'Blind Format String',
    category: 'technique',
    stack: [],
    format: ['format-string'],
    heap: [],
    sandbox: [],
    description: 'Exploits format string vulnerabilities when output is not visible (blind)',
    prerequisites: ['Vulnerability is accessible but output is suppressed'],
    constraints: ['Requires time-based or crash-based side channels'],
    blueprint: 'blind_bof() {\n  dump_binary_via_brop_like();\n}',
    children: [],
  },

  // HEAP EXPLOIT BRANCH
  heap_exploit: {
    id: 'heap_exploit',
    name: 'Heap Exploit',
    category: 'recon',
    stack: [],
    format: [],
    heap: ['heap-based'],
    sandbox: [],
    description: 'Exploits heap metadata and allocator behavior for code execution',
    prerequisites: ['Heap overflow', 'Allocator implementation knowledge'],
    constraints: ['Heap layout control', 'Metadata accessible'],
    blueprint: 'heap_exploit() {\n  corrupt_heap_metadata();\n  trigger_allocator_vuln();\n  achieve_code_exec();\n}',
    children: ['use_after_free', 'double_free', 'house_of_botcake', 'house_of_rabbit', 'house_of_roman', 'tcache_stashing', 'house_of_force', 'house_of_spirit', 'house_of_einherjar', 'unsorted_bin_attack', 'large_bin_attack'],
  },

  use_after_free: {
    id: 'use_after_free',
    name: 'Use-After-Free',
    category: 'technique',
    stack: [],
    format: [],
    heap: ['heap-based'],
    sandbox: [],
    description: 'Accesses memory after it has been freed, enabling exploitation',
    prerequisites: ['Memory free call accessible', 'Dangling pointer usage'],
    constraints: ['Heap state predictability', 'Object reuse timing'],
    blueprint: 'uaf_exploit() {\n  const obj = allocate_object();\n  free(obj);\n  reallocate_controlled();\n  use_freed_pointer(obj);\n}',
    children: ['heap_spray', 'vtable_hijack'],
  },

  double_free: {
    id: 'double_free',
    name: 'Double Free',
    category: 'technique',
    stack: [],
    format: [],
    heap: ['heap-based'],
    sandbox: [],
    description: 'Frees the same memory twice to corrupt heap state',
    prerequisites: ['Control over free calls', 'Allocator checks disabled'],
    constraints: ['Ptmalloc/jemalloc specific', 'Glibc version dependent'],
    blueprint: 'double_free() {\n  const ptr = allocate();\n  free(ptr);\n  free(ptr);  // Double free\n  reallocate_for_control();\n}',
    children: ['heap_control'],
  },

  vtable_hijack: {
    id: 'vtable_hijack',
    name: 'VTable Hijack',
    category: 'leaf',
    stack: [],
    format: [],
    heap: ['heap-based'],
    sandbox: [],
    description: 'Corrupts C++ vtable pointers to redirect virtual function calls',
    prerequisites: ['C++ object vulnerability', 'Heap write primitive'],
    constraints: ['VTable addressable', 'Method called after corruption'],
    blueprint: 'hijack_vtable() {\n  const obj = get_vulnerable_object();\n  obj.vtable = fake_vtable_addr;\n  obj.virtual_method();  // Redirected\n}',
    children: [],
  },

  heap_control: {
    id: 'heap_control',
    name: 'Heap Control',
    category: 'leaf',
    stack: [],
    format: [],
    heap: ['heap-based'],
    sandbox: [],
    description: 'Achieves arbitrary allocation control for object placement',
    prerequisites: ['Heap corruption', 'Allocator state manipulation'],
    constraints: ['Size class alignment', 'Bin management knowledge'],
    blueprint: 'control_heap() {\n  corrupt_heap_bins();\n  allocate_target_size();\n  return get_predictable_chunk();\n}',
    children: [],
  },

  house_of_force: {
    id: 'house_of_force',
    name: 'House of Force',
    category: 'technique',
    stack: [],
    format: [],
    heap: ['heap-based'],
    sandbox: [],
    description: 'Overwriting the Top Chunk (wilderness) size to -1, enabling massive mallocs that wrap around the address space to return a pointer anywhere in memory.',
    prerequisites: ['Heap overflow', 'Glibc < 2.29'],
    constraints: ['Target address must be at a higher address than heap base'],
    blueprint: 'force() {\n  overwrite_top_chunk_size(-1);\n  malloc(target - top_chunk - 0x20);\n  malloc(0x10); // Returns target ptr\n}',
    children: ['heap_control'],
  },

  house_of_spirit: {
    id: 'house_of_spirit',
    name: 'House of Spirit',
    category: 'technique',
    stack: [],
    format: [],
    heap: ['heap-based'],
    sandbox: [],
    description: 'Forging a fake chunk structure on the stack (or .bss) and passing its address to free(), putting the stack pointer into the fastbin.',
    prerequisites: ['Ability to call free() on arbitrary address', 'Stack/BSS write access'],
    constraints: ['Must forge valid chunk size and next chunk size'],
    blueprint: 'spirit() {\n  forge_chunk_on_stack(0x40, 0x1234);\n  free(stack_ptr);\n  malloc(0x30); // Returns stack ptr\n}',
    children: ['heap_control'],
  },

  house_of_einherjar: {
    id: 'house_of_einherjar',
    name: 'House of Einherjar',
    category: 'technique',
    stack: [],
    format: [],
    heap: ['heap-based'],
    sandbox: [],
    description: 'A single-byte overflow (off-by-one) sets the PREV_INUSE bit of the next chunk to 0, forcing backward consolidation with a fake chunk to overlap memory.',
    prerequisites: ['Off-by-one NULL byte overflow', 'Heap leak'],
    constraints: ['Complex fake chunk setup (fd/bk pointers)'],
    blueprint: 'einherjar() {\n  forge_fake_chunk_in_heap();\n  off_by_one_null_byte();\n  free(next_chunk); // Consolidates backward\n}',
    children: ['heap_control'],
  },

  unsorted_bin_attack: {
    id: 'unsorted_bin_attack',
    name: 'Unsorted Bin Attack',
    category: 'technique',
    stack: [],
    format: [],
    heap: ['heap-based'],
    sandbox: [],
    description: 'Corrupting the bk pointer of an unsorted bin chunk to write a large libc pointer (main_arena+88) to an arbitrary memory location.',
    prerequisites: ['UAF or Overflow on unsorted bin chunk'],
    constraints: ['Only writes a fixed libc address, cannot control the value'],
    blueprint: 'unsorted_attack() {\n  chunk->bk = target_addr - 0x10;\n  malloc(0); // Unlinks and writes libc ptr to target\n}',
    children: ['heap_control'],
  },

  large_bin_attack: {
    id: 'large_bin_attack',
    name: 'Large Bin Attack',
    category: 'technique',
    stack: [],
    format: [],
    heap: ['heap-based'],
    sandbox: [],
    description: 'Corrupting the fd_nextsize or bk_nextsize of a large bin chunk to achieve an arbitrary write when chunks are sorted/inserted into the large bin.',
    prerequisites: ['Ability to allocate large chunks (>0x400)', 'Heap vulnerability'],
    constraints: ['Writes a heap pointer, not an arbitrary value'],
    blueprint: 'large_bin() {\n  corrupt_bk_nextsize(target - 0x20);\n  malloc(large_size); // Triggers insertion and write\n}',
    children: ['heap_control'],
  },

  house_of_botcake: {
    id: 'house_of_botcake',
    name: 'House of Botcake',
    category: 'technique',
    stack: [],
    format: [],
    heap: ['heap-based'],
    sandbox: [],
    description: 'Bypasses tcache double-free checks by consolidating a large chunk, then freeing a smaller enclosed chunk to tcache',
    prerequisites: ['Glibc 2.29-2.31+', 'Ability to allocate and free 7 chunks (fill tcache)'],
    constraints: ['Needs overlapping chunks capability'],
    blueprint: 'botcake() {\n  fill_tcache();\n  free(prev); free(target); // consolidate\n  free(target); // to tcache\n}',
    children: ['heap_control'],
  },

  house_of_rabbit: {
    id: 'house_of_rabbit',
    name: 'House of Rabbit',
    category: 'technique',
    stack: [],
    format: [],
    heap: ['heap-based'],
    sandbox: [],
    description: 'Exploits malloc_consolidate to link fake chunks into fastbins and bypass checks',
    prerequisites: ['Large allocation capability', 'Heap info leak'],
    constraints: ['Very precise size formatting needed'],
    blueprint: 'rabbit() {\n  trigger_malloc_consolidate();\n  forge_fastbin();\n}',
    children: ['heap_control'],
  },

  house_of_roman: {
    id: 'house_of_roman',
    name: 'House of Roman',
    category: 'technique',
    stack: [],
    format: [],
    heap: ['heap-based'],
    sandbox: [],
    description: 'ASLR bypass for fastbin double free/unsorted bin attack using partial byte overwrites without leaks',
    prerequisites: ['Heap vulnerability (UAF/overflow)', 'No libc leak needed'],
    constraints: ['Requires 12-bit brute force (1/4096 success rate)'],
    blueprint: 'roman() {\n  overwrite_lsb_fd();\n  unsorted_bin_attack_lsb();\n}',
    children: ['heap_control'],
  },

  tcache_stashing: {
    id: 'tcache_stashing',
    name: 'Tcache Stashing Unlink',
    category: 'technique',
    stack: [],
    format: [],
    heap: ['heap-based'],
    sandbox: [],
    description: 'Uses calloc to bypass tcache and trigger small bin unlinking, corrupting the bk pointer to arbitrary write',
    prerequisites: ['calloc usage', 'Glibc 2.26-2.31', 'Ability to fill tcache'],
    constraints: ['Requires specific bin layout'],
    blueprint: 'stashing() {\n  corrupt_small_bin_bk();\n  calloc(); // triggers stash\n}',
    children: ['heap_control'],
  },

  // FSOP BRANCH
  fsop_exploit: {
    id: 'fsop_exploit',
    name: 'File Stream Exploitation (FSOP)',
    category: 'recon',
    stack: [],
    format: [],
    heap: ['heap-based'], // often combined with heap
    sandbox: [],
    description: 'File Stream Oriented Programming - corrupts _IO_FILE structures (like stdin, stdout, stderr) to hijack control flow',
    prerequisites: ['Arbitrary write or heap overflow on FILE structs'],
    constraints: ['Glibc version specific vtable mitigations'],
    blueprint: 'fsop() {\n  corrupt_FILE_vtable();\n  trigger_IO_flush();\n}',
    children: ['house_of_apple', 'house_of_orange'],
  },

  house_of_apple: {
    id: 'house_of_apple',
    name: 'House of Apple (1 & 2)',
    category: 'technique',
    stack: [],
    format: [],
    heap: ['heap-based'],
    sandbox: [],
    description: 'Exploits modern glibc by hijacking _IO_FILE chains via _IO_wstr_jumps or _IO_wfile_jumps to achieve RCE',
    prerequisites: ['Glibc 2.34+ (post-hook removal)', 'Large arbitrary write'],
    constraints: ['Complex fake struct setup required'],
    blueprint: 'apple() {\n  forge_wide_data();\n  set_vtable_to_wstr_jumps();\n}',
    children: [],
  },

  house_of_orange: {
    id: 'house_of_orange',
    name: 'House of Orange',
    category: 'technique',
    stack: [],
    format: [],
    heap: ['heap-based'],
    sandbox: [],
    description: 'Corrupts top chunk size to trigger sysmalloc, yielding an unsorted bin chunk, then uses FSOP to get RCE during abort()',
    prerequisites: ['No free() call available', 'Glibc < 2.26'],
    constraints: ['Relies on abort() triggering _IO_flush_all_lockp'],
    blueprint: 'orange() {\n  corrupt_top_chunk();\n  trigger_sysmalloc();\n  fsop_via_unsorted_bin();\n}',
    children: [],
  },

  // SANDBOX ESCAPE BRANCH
  sandbox_escape: {
    id: 'sandbox_escape',
    name: 'Sandbox Escape',
    category: 'recon',
    stack: [],
    format: [],
    heap: [],
    sandbox: ['sandbox-escape'],
    description: 'Breaks out of restricted execution environments (browsers, containers)',
    prerequisites: ['Sandbox architecture knowledge', 'IPC vulnerabilities'],
    constraints: ['Mitigation bypass required', 'Privilege escalation needed'],
    blueprint: 'sandbox_escape() {\n  const vuln = find_ipc_vulnerability();\n  escalate_privileges();\n  break_out_of_sandbox();\n}',
    children: ['privilege_escalation', 'ipc_exploit', 'dirty_cow', 'modprobe_path', 'ebpf_exploit'],
  },

  privilege_escalation: {
    id: 'privilege_escalation',
    name: 'Privilege Escalation',
    category: 'technique',
    stack: [],
    format: [],
    heap: [],
    sandbox: ['sandbox-escape'],
    description: 'Elevates permissions from restricted to unrestricted execution',
    prerequisites: ['Kernel vulnerability', 'SUID binary', 'Capability error'],
    constraints: ['Kernel version specific', 'Patch level dependent'],
    blueprint: 'escalate() {\n  const exploit = load_kernel_exploit();\n  exploit.execute();\n  verify_root_access();\n}',
    children: ['kernel_rce', 'capability_abuse', 'ret2usr'],
  },

  ipc_exploit: {
    id: 'ipc_exploit',
    name: 'IPC Vulnerability',
    category: 'technique',
    stack: [],
    format: [],
    heap: [],
    sandbox: ['sandbox-escape'],
    description: 'Exploits inter-process communication to send malicious messages',
    prerequisites: ['IPC interface accessible', 'Message validation weak'],
    constraints: ['Broker implementation details', 'Message format specific'],
    blueprint: 'exploit_ipc() {\n  const channel = create_ipc_channel();\n  const payload = craft_malicious_message();\n  send_to_broker(channel, payload);\n}',
    children: ['mojo_exploit'],
  },

  kernel_rce: {
    id: 'kernel_rce',
    name: 'Kernel RCE',
    category: 'leaf',
    stack: [],
    format: [],
    heap: [],
    sandbox: ['sandbox-escape'],
    description: 'Achieves remote code execution in kernel space',
    prerequisites: ['Kernel vulnerability', 'Working exploit PoC'],
    constraints: ['SMEP/SMAP evasion', 'KASLR bypass'],
    blueprint: 'kernel_rce() {\n  const rip = leak_kernel_addr();\n  const chain = build_kernel_rop(rip);\n  trigger_kernel_crash(chain);\n}',
    children: ['msg_msg_corruption', 'userfaultfd_exploit'],
  },

  msg_msg_corruption: {
    id: 'msg_msg_corruption',
    name: 'msg_msg Struct Corruption',
    category: 'leaf',
    stack: [],
    format: [],
    heap: [],
    sandbox: ['sandbox-escape'],
    description: 'Corrupting the m_ts (size) or m_list pointers in the kernel msg_msg structure to achieve arbitrary read/write in kernel heap (kmalloc).',
    prerequisites: ['Kernel heap out-of-bounds or UAF', 'CONFIG_SYSVIPC enabled'],
    constraints: ['Requires precise kernel heap shaping (SLUB allocator)'],
    blueprint: 'msg_msg_exploit() {\n  spray_msg_msg();\n  trigger_oob_write_corrupt_size();\n  read_msg_for_leak();\n}',
    children: [],
  },

  userfaultfd_exploit: {
    id: 'userfaultfd_exploit',
    name: 'userfaultfd Exploitation',
    category: 'leaf',
    stack: [],
    format: [],
    heap: [],
    sandbox: ['sandbox-escape'],
    description: 'Using userfaultfd to pause kernel execution during a copy_from_user call, widening race condition windows infinitely for TOCTOU attacks.',
    prerequisites: ['userfaultfd syscall allowed', 'Race condition vulnerability'],
    constraints: ['Blocked in newer kernels for unprivileged users (unprivileged_userfaultfd=0)'],
    blueprint: 'uffd() {\n  setup_uffd_page();\n  trigger_kernel_copy_from_user();\n  // execution pauses\n  swap_pointers_in_another_thread();\n  release_uffd();\n}',
    children: [],
  },

  ebpf_exploit: {
    id: 'ebpf_exploit',
    name: 'eBPF Verifier Bypass',
    category: 'technique',
    stack: [],
    format: [],
    heap: [],
    sandbox: ['sandbox-escape'],
    description: 'Exploiting flaws in the eBPF verifier\'s static analysis to trick it into loading malicious BPF programs that can read/write kernel memory.',
    prerequisites: ['CAP_BPF or unprivileged bpf allowed'],
    constraints: ['Kernel patch dependent, highly complex'],
    blueprint: 'ebpf_exploit() {\n  craft_malicious_bpf_bytecode();\n  bypass_verifier_bounds_check();\n  bpf_map_update_elem_arb_write();\n}',
    children: ['kernel_rce'],
  },

  capability_abuse: {
    id: 'capability_abuse',
    name: 'Capability Abuse',
    category: 'leaf',
    stack: [],
    format: [],
    heap: [],
    sandbox: ['sandbox-escape'],
    description: 'Misuses Linux capabilities for privilege escalation',
    prerequisites: ['CAP_SYS_ADMIN available', 'Capability misconfiguration'],
    constraints: ['Container/namespace setup'],
    blueprint: 'abuse_capability() {\n  const cap = get_available_capability();\n  use_for_privilege_escalation();\n  spawn_unrestricted_shell();\n}',
    children: [],
  },

  mojo_exploit: {
    id: 'mojo_exploit',
    name: 'Mojo/IPC RCE',
    category: 'leaf',
    stack: [],
    format: [],
    heap: [],
    sandbox: ['sandbox-escape'],
    description: 'Exploits Mojo IPC framework in browser/container environments',
    prerequisites: ['Mojo interface defined', 'Type confusion possible'],
    constraints: ['Mojo version specific', 'Serialization details'],
    blueprint: 'exploit_mojo() {\n  const binding = create_mojo_binding();\n  const rce = build_type_confusion();\n  send_exploit_message(rce);\n}',
    children: [],
  },

  dirty_cow: {
    id: 'dirty_cow',
    name: 'Dirty COW (CVE-2016-5195)',
    category: 'technique',
    stack: [],
    format: [],
    heap: [],
    sandbox: ['sandbox-escape'],
    description: 'Exploits a race condition in Linux memory management (Copy-On-Write) to write to read-only files (like /etc/passwd or SUID binaries)',
    prerequisites: ['Kernel < 4.8.3', 'Local access'],
    constraints: ['Can cause system instability'],
    blueprint: 'dirty_cow() {\n  mmap_read_only_file();\n  thread1_madvise_dontneed();\n  thread2_write_proc_self_mem();\n}',
    children: [],
  },

  modprobe_path: {
    id: 'modprobe_path',
    name: 'modprobe_path Overwrite',
    category: 'leaf',
    stack: [],
    format: [],
    heap: [],
    sandbox: ['sandbox-escape'],
    description: 'Kernel exploit technique that overwrites core_pattern or modprobe_path to execute an arbitrary script as root',
    prerequisites: ['Arbitrary write in kernel space'],
    constraints: ['Requires KASLR bypass to find modprobe_path'],
    blueprint: 'modprobe() {\n  write_kernel_addr(modprobe_path, "/tmp/x");\n  trigger_unknown_executable();\n}',
    children: [],
  },

  ret2usr: {
    id: 'ret2usr',
    name: 'ret2usr',
    category: 'leaf',
    stack: [],
    format: [],
    heap: [],
    sandbox: ['sandbox-escape'],
    description: 'Kernel exploitation technique that redirects kernel execution to a user-space function to escalate privileges',
    prerequisites: ['Kernel arbitrary execution', 'SMEP disabled'],
    constraints: ['Blocked by SMEP (Supervisor Mode Execution Protection)'],
    blueprint: 'ret2usr() {\n  hijack_kernel_ptr(user_space_payload);\n  // user_space_payload: commit_creds(prepare_kernel_cred(0))\n}',
    children: [],
  },

  // INTEGER EXPLOITS BRANCH
  integer_exploits: {
    id: 'integer_exploits',
    name: 'Integer Vulnerabilities',
    category: 'root',
    stack: [],
    format: [],
    heap: [],
    sandbox: [],
    description: 'Vulnerabilities stemming from how computers store and calculate numbers, often leading to buffer overflows or logic flaws.',
    prerequisites: [],
    constraints: [],
    blueprint: 'integer_analysis() {\n  check_variable_types();\n  find_unsigned_to_signed_casts();\n  find_allocation_size_math();\n}',
    children: ['integer_overflow', 'integer_underflow', 'sign_extension', 'off_by_one'],
  },

  integer_overflow: {
    id: 'integer_overflow',
    name: 'Integer Overflow',
    category: 'recon',
    stack: ['stack-based'],
    format: [],
    heap: ['heap-based'],
    sandbox: [],
    description: 'An arithmetic operation attempts to create a numeric value that is larger than can be represented within the available storage space (e.g., 0xFFFFFFFF + 1 = 0x00000000).',
    prerequisites: ['Unchecked arithmetic on allocation sizes or array indexes'],
    constraints: [],
    blueprint: 'int_overflow() {\n  send_size(0xFFFFFFFF);\n  // triggers malloc(0) but loops 0xFFFFFFFF times\n}',
    children: ['buffer_overflow', 'heap_exploit'],
  },

  integer_underflow: {
    id: 'integer_underflow',
    name: 'Integer Underflow',
    category: 'recon',
    stack: ['stack-based'],
    format: [],
    heap: ['heap-based'],
    sandbox: [],
    description: 'Subtracting below zero on an unsigned integer causes it to wrap around to its maximum value (e.g., 0 - 1 = 0xFFFFFFFF).',
    prerequisites: ['Unchecked subtraction'],
    constraints: [],
    blueprint: 'int_underflow() {\n  send_size(0);\n  // size - 1 becomes 0xFFFFFFFF\n  trigger_bof();\n}',
    children: ['buffer_overflow'],
  },

  sign_extension: {
    id: 'sign_extension',
    name: 'Sign Extension Vulnerability',
    category: 'technique',
    stack: ['stack-based'],
    format: [],
    heap: [],
    sandbox: [],
    description: 'Casting a signed negative smaller integer (e.g., char -1) to a larger integer (e.g., int) fills the upper bits with 1s, resulting in a huge unsigned value.',
    prerequisites: ['Implicit or explicit cast from signed narrow to wider type'],
    constraints: [],
    blueprint: 'sign_extend() {\n  char length = -1; // 0xFF\n  int new_length = length; // 0xFFFFFFFF\n}',
    children: ['buffer_overflow'],
  },

  off_by_one: {
    id: 'off_by_one',
    name: 'Off-By-One Error',
    category: 'technique',
    stack: ['stack-based'],
    format: [],
    heap: ['heap-based'],
    sandbox: [],
    description: 'A logic error involving boundaries where a loop iterates one time too many or too few, allowing exactly 1 byte to be overwritten past a buffer.',
    prerequisites: ['for(int i=0; i<=length; i++) or similar boundary flaw'],
    constraints: ['Only 1 byte of overflow'],
    blueprint: 'off_by_one() {\n  // overwrite saved RBP LSB on stack\n  // or overwrite chunk PREV_INUSE bit on heap\n}',
    children: ['stack_pivot', 'house_of_einherjar'],
  },
};

export const getChildrenIds = (parentId: string): string[] => {
  return PWN_TECHNIQUES[parentId]?.children || [];
};

export const getTechniquesByCategory = (category: keyof typeof PWN_TECHNIQUES): Technique[] => {
  return Object.values(PWN_TECHNIQUES).filter((t) => t.category === category);
};
